version: 0.1

phases:
  pre_build:
    commands:
      - echo Prebuild ops

  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    
    
    phases:
  pre_build:
    commands:
      - echo Prebuild ops

  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
